server:
  port: 8763

spring:
  application:
    name: service-lucy

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
